In [1]:
import pandas as pd
import urllib.request
import zipfile

In [2]:
#Download ZIP archive from FFIEC Census site and extract it
ffiec_census_url = "https://www.ffiec.gov/Census/Census_Flat_Files/CENSUS2019.zip"
urllib.request.urlretrieve(ffiec_census_url, "../data/ffiec_census_2019.zip")
with zipfile.ZipFile("../data/ffiec_census_2019.zip", 'r') as zip_ref:
    zip_ref.extractall("../data/")

In [3]:
#load FFIEC Census file and extract relevant fields and resave them
#MFI = median family income
ffiec_census_df = pd.read_csv("../data/Census2019.csv", header=None)
col_names = {0:"hmda_year", 
             1:"msa_md", 
             2:"state_fips", 
             3:"county_fips", 
             4:"census_tract", 
             12:"tract_to_msa_mfi_pct",
             13:"ffiec_mfi",
             14:"total_persons", 
             20:"minority_population_pct", 
             580:"tract_mfi",
             899:"total_1_4_family_units",
             915:"owner_occupied_units", 
             952:"median_housing_age"}

#get MSA, state, county, tract codes
ffiec_census_df = ffiec_census_df.iloc[:, [0,1,2,3,4,13,14,20,915,899,580,12,952]].copy()
ffiec_census_df.rename(columns=col_names, inplace=True)
print(len(ffiec_census_df))
ffiec_census_df.head()

75883

,hmda_year,msa_md,state_fips,county_fips,census_tract,ffiec_mfi,total_persons,minority_population_pct,owner_occupied_units,total_1_4_family_units,tract_mfi,tract_to_msa_mfi_pct,median_housing_age
0,2019,33860,1,1,20100,65900,1948,12.58,507.0,724.0,72727,122.93,36.0
1,2019,33860,1,1,20200,65900,2156,59.55,433.0,785.0,48750,82.40,39.0
2,2019,33860,1,1,20300,65900,2968,25.47,828.0,1327.0,55766,94.26,39.0
3,2019,33860,1,1,20400,65900,4423,17.21,1345.0,1806.0,69114,116.82,46.0
4,2019,33860,1,1,20500,65900,10763,31.54,2255.0,3237.0,75574,127.74,14.0

In [4]:
ffiec_census_df.to_csv("../output/ffiec_census_2019.txt", sep="|", index=False)